version: "3.8"
services:
  db:
    image: "mongo:4"
    volumes:
      - /data/up-db
    ports:
      - "27017:27017"
  server:
    build:
      context: .
      dockerfile: docker/Dockerfile.server
    ports:
      - "4000:4000"
    env_file:
      - ./packages/server/.env
    depends_on:
      - db
    environment:
      - DB_URL=mongodb://db:27017
  client:
    build:
      context: .
      dockerfile: docker/Dockerfile.client
      args:
        VITE_API_URL: "http://localhost:4000/graphql"
    ports:
      - "5000:80"
    stdin_open: true
    tty: true