FROM node:20 AS build

WORKDIR /app/client

COPY client/package.json client/yarn.lock /app/client/

RUN yarn --production

COPY client /app/client

COPY shared /app/shared

RUN yarn codegen

RUN yarn build

FROM nginx:1-alpine

COPY --from=build /app/client/dist /usr/share/nginx/html

