FROM node:20 AS build

WORKDIR /app/client

COPY client/package.json client/yarn.lock /app/client/

RUN yarn

COPY client /app/client

COPY shared /app/shared

RUN yarn codegen

CMD ["yarn", "start"]

