services:
  up-db:
    image: mongo:4
    volumes: 
      - /data/compose-db
  server:
    build: 
      dockerfile: Dockerfile.server
      context: .
    depends_on:
      - up-db
    env_file: "./server/.env"
    ports:
      - 4000:4000
  client:
    build:
      dockerfile: Dockerfile.client
      context: .
    environment:
      - VITE_API_URL=http://localhost:4000/graphql
    depends_on:
      - server
    ports:
      - 5000:80

volumes:
  data: