FROM node:20.15.1

ENV YARN_VERSION=1.22.19

RUN yarn set version ${YARN_VERSION}

WORKDIR /app

COPY package.json yarn.lock lerna.json /app/

COPY packages/server /app/packages/server
COPY packages/shared /app/packages/shared
COPY packages/tsconfig.settings.json /app/packages

RUN yarn install

RUN yarn build:server

RUN rm -rf /app/packages/server/src

RUN chown -R  node:node /app/

USER node

WORKDIR /app/packages/server

CMD ["node", "dist/server.js"]

