name: Build and Push Docker Images

on:
  push:
    branches: [ts-monorepo-ci, develop]
  pull_request:
    branches: [master, develop]

jobs:
  lint:
    runs-on: ubuntu-22.04
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20.15.1"
      - name: Configure yarn
        run: yarn set version 4.3.1
      - name: Cache node_modules
        id: cache-nodemodules
        uses: actions/cache@v3
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
      - name: Install dependencies
        if: steps.cache-nodemodules.outputs.cache-hit != 'true'
        run: yarn install --frozen-lockfile
      - run: yarn lint

  test:
    runs-on: ubuntu-22.04
    needs: lint
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20.15.1"
      - uses: ./.github/actions/setup-yarn
      - uses: ./.github/actions/setup-mongodb
        with:
          mongodb-version: "4.0"
      - run: yarn codegen
      - run: yarn test

  cypress:
    needs: lint
    permissions:
      contents: read
    env:
      VITE_API_URL: http://localhost:4000/graphql
      FE_URL: http://localhost:5000
      PLANETS_API: ${{ secrets.PLANETS_API }}
      STARSHIP_API: ${{ secrets.STARSHIP_API }}
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20.15.1"
      - uses: ./.github/actions/setup-yarn
      - uses: ./.github/actions/setup-mongodb
        with:
          mongodb-version: "4.0"
      - name: Cache Cypress binary
        uses: actions/cache@v3
        with:
          path: ~/.cache/Cypress
          key: cypress-${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}
      - name: Generate code
        run: yarn codegen
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          working-directory: .
          install-command: yarn install --frozen-lockfile
          start: yarn start
          wait-on: "http://localhost:5000"
          project: ./packages/client
      - name: Upload Cypress screenshots
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: cypress-screenshots
          path: packages/client/cypress/screenshots

  build-and-push:
    needs: [lint, test, cypress]
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push server image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: docker/Dockerfile.server
          push: true
          tags: mganza/up-and-running:server
      - name: Build and push client image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: docker/Dockerfile.client
          push: true
          tags: mganza/up-and-running:client

  notify:
    needs: [lint, test, cypress, build-and-push]
    if: failure()
    permissions:
      contents: read
    runs-on: ubuntu-22.04
    steps:
      - name: Send Slack notification
        uses: slackapi/slack-github-action@v1.24.0
        with:
          channel-id: ${{ secrets.SLACK_CHANNEL_ID }}
          payload: |
            {
              "text": "Workflow Failed!",
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "*Workflow Failed* :x:\n Repository: ${{ github.repository }}\n Branch: ${{ github.ref }}"
                  }
                },
                {
                  "type": "actions",
                  "elements": [
                    {
                      "type": "button",
                      "text": {
                        "type": "plain_text",
                        "text": "View Failed Action"
                      },
                      "url": "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
                    }
                  ]
                }
              ]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
  notify-success:
    needs: build-and-push
    runs-on: ubuntu-22.04
    steps:
      - name: Send Slack notification
        uses: slackapi/slack-github-action@v1.24.0
        with:
          channel-id: ${{ secrets.SLACK_CHANNEL_ID }}
          payload: |
            {
              "text": "New Docker images uploaded successfully!",
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "*New Docker images uploaded* :white_check_mark:\nRepository: ${{ github.repository }}\nBranch: ${{ github.ref }}"
                  }
                },
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "*Server Image:* <https://hub.docker.com/r/mganza/up-and-running/tags?name=server|mganza/up-and-running:server>\n*Client Image:* <https://hub.docker.com/r/mganza/up-and-running/tags?name=client|mganza/up-and-running:client>"
                  }
                },
                {
                  "type": "actions",
                  "elements": [
                    {
                      "type": "button",
                      "text": {
                        "type": "plain_text",
                        "text": "View Workflow Run"
                      },
                      "url": "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
                    }
                  ]
                }
              ]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
