name: Ready
on:
  push:
    branches: [ts-monorepo-ci, develop]
  pull_request:
    branches: [master, develop]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20.15.1"
      - name: Configure yarn
        run: yarn set version 4.3.1
      - name: Cache node_modules
        id: cache-nodemodules
        uses: actions/cache@v3
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
      - name: Install dependencies
        if: steps.cache-nodemodules.outputs.cache-hit != 'true'
        run: yarn install --frozen-lockfile
      - run: yarn lint

  test:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20.15.1"
      - uses: ./.github/actions/setup-yarn
      - uses: ./.github/actions/setup-mongodb
        with:
          mongodb-version: "4.0"
      - run: yarn codegen
      - run: yarn test

  cypress:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20.15.1"
      - uses: ./.github/actions/setup-yarn
      - uses: ./.github/actions/setup-mongodb
        with:
          mongodb-version: "4.0"
      - name: Cache Cypress binary
        uses: actions/cache@v3
        with:
          path: ~/.cache/Cypress
          key: cypress-${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}
      - name: Generate code
        run: yarn codegen
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          install-command: yarn install --frozen-lockfile
          start: yarn start
          wait-on: "http://localhost:5000"
      - name: Upload Cypress screenshots
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: cypress-screenshots
          path: cypress/screenshots
