name: Up and Running
on:
  push:
    branches: [ts-monorepo-ci, develop]
  pull_request:
    branches: [master, develop]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "18"
      - run: yarn
      - run: yarn lint
