name: Ready
on:
  push:
    branches: [ts-monorepo-ci, develop]
  pull_request:
    branches: [master, develop]

jobs:
  lint:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20.15.1"
      - name: Configure yarn
        run: yarn set version 4.3.1
      - name: Cache node_modules
        id: cache-nodemodules
        uses: actions/cache@v3
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
      - name: Install dependencies
        if: steps.cache-nodemodules.outputs.cache-hit != 'true'
        run: yarn install --frozen-lockfile
      - run: yarn lint

  test:
    runs-on: ubuntu-22.04
    needs: lint
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20.15.1"
      - uses: ./.github/actions/setup-yarn
      - uses: ./.github/actions/setup-mongodb
        with:
          mongodb-version: "4.0"
      - run: yarn codegen
      - run: yarn test

  cypress:
    needs: lint
    env:
      VITE_API_URL: http://localhost:4000/graphql
      FE_URL: http://localhost:5000
      PLANETS_API: ${{ secrets.PLANETS_API }}
      STARSHIP_API: ${{ secrets.STARSHIP_API }}
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20.15.1"
      - uses: ./.github/actions/setup-yarn
      - uses: ./.github/actions/setup-mongodb
        with:
          mongodb-version: "4.0"
      - name: Cache Cypress binary
        uses: actions/cache@v3
        with:
          path: ~/.cache/Cypress
          key: cypress-${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}
      - name: Generate code
        run: yarn codegen
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          working-directory: .
          install-command: yarn install --frozen-lockfile
          start: yarn start
          wait-on: "http://localhost:5000"
          project: ./packages/client
      - name: Upload Cypress screenshots
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: cypress-screenshots
          path: packages/client/cypress/screenshots

  notify:
    needs: [lint, test, cypress]
    if: failure()
    runs-on: ubuntu-22.04
    steps:
      - name: Download Cypress screenshots
        uses: actions/download-artifact@v4
        # if: failure()
        with:
          name: cypress-screenshots
          path: cypress-screenshots

      - name: Send Slack notification
        uses: slackapi/slack-github-action@v1.24.0
        with:
          channel-id: ${{ secrets.SLACK_CHANNEL_ID }}
          payload: |
            {
              "text": "Workflow Failed!",
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "*Workflow Failed* :x:\nRepository: ${{ github.repository }}\nBranch: ${{ github.ref }}"
                  }
                },
                {
                  "type": "actions",
                  "elements": [
                    {
                      "type": "button",
                      "text": {
                        "type": "plain_text",
                        "text": "View Failed Action"
                      },
                      "url": "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
                    }
                  ]
                }
              ]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK

      - name: Upload Screenshots to Slack
        # if: failure()
        run: |
          for file in cypress-screenshots/*.png; do
            if [ -f "$file" ]; then
              curl -F file=@"$file" \
                   -F "initial_comment=Cypress Failure Screenshot: $(basename "$file")" \
                   -F channels="${{ secrets.SLACK_CHANNEL_ID }}" \
                   -H "Authorization: Bearer ${{ secrets.SLACK_BOT_TOKEN }}" \
                   https://slack.com/api/files.upload
            fi
          done
